// client_react/src/components/Auth/SignIn/SignIn.js
import { h, Component } from 'preact';
import { Link } from 'preact-router';
import TextField from '../../../components/ui/TextField';
import Button from '../../../components/ui/Button';

export default class SignIn extends Component {
  state = {};

  // eslint-disable-next-line class-methods-use-this
  render() {
    return (
      <div className="min-h-screen flex items-center justify-center flex-col">
        <h1 className="text-4xl font-bold">Sign in.</h1>
        <form className="w-full md:max-w-lg mx-auto p-4">
          <div className="mb-4">
            <TextField
              id="email"
              type="text"
              placeholder="eg. user@gmail.com"
              label="Email"
              name="email"
              required
            />
          </div>
          <div className="mb-6">
            <TextField
              id="password"
              type="text"
              placeholder="******************"
              label="Password"
              labelClasses="block text-gray-700 text-sm font-bold mb-2"
              classes="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
              name="password"
              required
            />
          </div>
          <div className="flex items-center justify-between">
            <Button
              buttonText="Sign In"
              classes="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
              type="submit"
            />
            <Link
              className="inline-block align-baseline font-bold text-sm text-blue-600 hover:text-blue-800"
              href="#"
            >
              Forgot Password?
            </Link>
          </div>
        </form>
      </div>
    );
  }
}

// client/src/views/Signin.vue
<template>
  <div class="min-h-screen flex flex-col items-center justify-center">
    <v-logotype class="mb-4" width="64" height="64" />
    <form @submit.prevent="signin" class="bg-white w-full md:w-1/3 p-4">
      <div class="mb-4">
        <label class="block text-sm font-bold mb-2" for="email">
          Email
        </label>
        <input
          class="
            appearance-none
            border
            rounded
            w-full
            py-2
            px-3
            leading-tight
            focus:border-black
            focus:outline-none
            focus:shadow
          "
          id="email"
          type="email"
          required
          placeholder="email"
          v-model="form.email"
        />
      </div>
      <div class="mb-6">
        <label class="block text-sm font-bold mb-2" for="password">
          Password
        </label>
        <input
          class="
            appearance-none
            border
            rounded
            w-full
            py-2
            px-3
            leading-tight
            focus:border-black
            focus:outline-none
            focus:shadow
          "
          id="password"
          required
          type="password"
          placeholder="******************"
          v-model="form.password"
        >
      </div>
      <div class="flex items-center justify-between">
        <button
          class="
            bg-black
            text-white
            font-bold
            py-2
            px-4
            rounded
            focus:outline-none
            focus:shadow-outline
          "
          type="submit"
        >
          Sign In
        </button>
        <router-link
          class="
            inline-block
            align-baseline
            font-bold
            text-sm
            text-gray-600
            hover:text-black
          "
          :to="{ name: 'Signup' }"
        >
          or Sign Up
        </router-link>
      </div>
    </form>
  </div>
</template>

<script>
import VLogotype from '@/components/Logotype.vue';

export default {
  data: () => ({
    form: {
      email: '',
      password: '',
    },
  }),
  methods: {
    signin() {
      return this.$fetch('/signin/', {
        hasToken: false,
        method: 'POST',
        body: JSON.stringify(this.form),
      })
        .then((response) => response.json())
        .then(({ token }) => {
          window.localStorage.setItem('token', token);
          this.$router.push({ name: 'Home' });
        })
        .catch((error) => window.console.log(error));
    },
  },
  components: { VLogotype },
};
</script>
